name: UserTP
author: BoxOfDevs Team
authors:
- TheDragonRing
- Riegert
- Ad5001
version: 1.0.0
description: A plugin with TPA-like features
api:
- 1.14.2
- 2.0.0
main: UserTP\Main
load: STARTUP
commands:
    tpa:
        usage: "/tpa invite|ask|accept|decline <player>"
        description: "Let's a user invite another player to them, ask to teleport to another player, and then accept or deny these requests"
        permission: usertp.command.main
    tpaall:
        usage: "/tpaall invite|ask"
        description: "Let's you teleport all players either to you, to another player, or to specified XYZ coordinates"
        permission: usertp.command.tpaall
   tpo:
        usage: "/tpo here|to <player>"
        description: "Teleport to a player or teleport him to you"
        permission: usertp.command.mainoblication
   tpoall:
        usage: "/tpoall here|to "
        description: "Teleport to a player or teleport him to you"
        permission: usertp.command.alloblication
permissions:
    usertp:
        default: false
        children:
            usertp.command:
            default: false
            children:
                usertp.command.main:
                    default: true
                usertp.command.tpaall:
                    default: true
                usertp.command.mainoblication:
                    default: op
                usertp.command.alloblication:
                    default: op
